version: '3'

services:
  mongodb:
    image: mongo:3.2.6
    container_name: mongodb
    ports:
      - 27017:27017

  bookstore-api:
    image: bookstore-api
    build:
      context: ./
    depends_on:
      - mongodb
    ports:
      - 8080:8080

  mongo-init:
    build: ./mongo-init
    depends_on:
      - mongodb